fix: invalid IntPtr Null check (#160)
* fix: invalid IntPtr Null check

`m_OverrideLibraryPath != null` was casuing the following error using warning level 5 and warnaserrors enabled:
```
error CS8073: The result of the expression is always 'true' since a value of type 'IntPtr' is never equal to 'null' of type 'IntPtr?'
```

* Found a couple more invalid IntPtr null checks